version: 1

profiles:
  default:
    readwrite_account: "default"
    readonly_account: "default"
    noaccess_account: "default"

  rad_external:
    readwrite_account: "readwrite1"
    readonly_account: "readonly1"
    noaccess_account: "noaccess1"

accounts:
  readwrite:
    default:
      source: "ems_local"
      username: "admin"
      password: "Pqa1234!!"
    readwrite1:
      username: "readwrite1"
      password: "readwrite1PW"
      source: "rad_external"

  readonly:
    default:
      source: "ems_local"
      username: "RestApiRO"
      password: "Pqa1234!!"
    readonly1:
      username: "readonly1"
      password: "readonly1PW"
      source: "rad_external"

  noaccess:
    default:
      source: "ems_local"
      username: "RestApiNA"
      password: "Pqa1234!!"
    noaccess1:
      username: "noaccess1"
      password: "noaccess1PW"
      source: "rad_external"
