from __future__ import annotations

import argparse
import csv
import json
import os
import subprocess
import sys
import xmlrpc.client
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from cases.case_catalog import catalog_test_cases
from cases.endpoint_cases import MUTATING_ENDPOINTS, READ_ENDPOINTS
from cases.neox_case_ids import DIRECT_NEOX_READWRITE_CASES, PROFILE_OPERATION_OFFSETS, PROFILE_TYPES
from cases.registry import AUTOMATED_CASES, TestCaseRecord
from models.api import EndpointCase


DEFAULT_OUTPUT = Path("reports/testlink_backfill_steps.json")
DEFAULT_AGENT_RESULTS = Path("reports/testlink_agent_backfill_results.json")


@dataclass(frozen=True)
class TestLinkStep:
    step_number: int
    actions: str
    expected_results: str
    execution_type: int = 2


@dataclass(frozen=True)
class TestLinkCaseBackfill:
    external_id: str
    name: str
    summary: str
    preconditions: str
    steps: list[TestLinkStep]
    source: str
    markers: list[str]


def build_backfill_cases() -> list[TestLinkCaseBackfill]:
    cases_by_id: dict[str, TestLinkCaseBackfill] = {}
    for endpoint in [*READ_ENDPOINTS, *MUTATING_ENDPOINTS]:
        if endpoint.case_id:
            cases_by_id[endpoint.case_id] = endpoint_backfill(endpoint)

    for record in AUTOMATED_CASES:
        cases_by_id.setdefault(record.case_id, record_backfill(record))

    for case in catalog_records():
        cases_by_id.setdefault(case.external_id, case)

    for case in neox_records():
        cases_by_id[case.external_id] = case

    return sorted((collapse_case_steps(case) for case in cases_by_id.values()), key=case_sort_key)


def collapse_case_steps(case: TestLinkCaseBackfill) -> TestLinkCaseBackfill:
    """Keep one TestLink step row and put the ordered test flow inside the fields."""
    if len(case.steps) <= 1:
        return case
    actions = "\n".join(f"{index}. {step.actions}" for index, step in enumerate(case.steps, start=1))
    expected = "\n".join(
        f"{index}. {step.expected_results}" for index, step in enumerate(case.steps, start=1)
    )
    return TestLinkCaseBackfill(
        external_id=case.external_id,
        name=case.name,
        summary=case.summary,
        preconditions=case.preconditions,
        steps=[TestLinkStep(1, actions, expected)],
        source=case.source,
        markers=case.markers,
    )


def endpoint_backfill(case: EndpointCase) -> TestLinkCaseBackfill:
    method = case.method.upper()
    path = describe_path(case)
    has_payload = case.payload_factory is not None
    has_params = case.params_factory is not None
    is_mutating = method in {"POST", "PUT", "PATCH", "DELETE"}
    action_detail = f"Call `{method} {path}`."
    if has_params:
        action_detail += " Include the query parameters or filters defined by the automation."
    if has_payload:
        action_detail += " Include the request body generated by the automation payload factory."

    steps = [
        TestLinkStep(
            1,
            "Log in to the EMS REST API with the required role account and obtain a valid session.",
            "Login succeeds and a usable session id is returned.",
        ),
        TestLinkStep(
            2,
            action_detail,
            expected_success_text(case.expected_success),
        ),
    ]
    if is_mutating:
        steps.append(
            TestLinkStep(
                3,
                "If the test creates or changes data, clean up the test data through the automation cleanup or fixture flow.",
                "Cleanup completes without affecting later test cases or the existing environment state.",
            )
        )
    else:
        steps.append(
            TestLinkStep(
                3,
                "Parse the response JSON and verify the returned API content against the configured test target.",
                "The response JSON is parseable, and required fields or target data match the current test configuration.",
            )
        )

    return TestLinkCaseBackfill(
        external_id=str(case.case_id),
        name=case.name,
        summary=f"Verify the EMS REST API `{case.name}` endpoint behavior.",
        preconditions=standard_preconditions(case.domain, mutating=is_mutating),
        steps=steps,
        source="cases.endpoint_cases",
        markers=[case.domain, method.lower(), *([] if not is_mutating else ["mutating"])],
    )


def record_backfill(record: TestCaseRecord) -> TestLinkCaseBackfill:
    if record.domain == "session":
        return session_backfill(record)
    if record.domain == "permission":
        return permission_summary_backfill(record)
    if record.domain == "authmatrix":
        return auth_matrix_summary_backfill(record)
    if record.domain == "openapi":
        return openapi_backfill(record)
    if "invalid_param" in record.name or "invalid_parameters" in record.name:
        return invalid_param_backfill(record)

    return TestLinkCaseBackfill(
        external_id=record.case_id,
        name=record.name,
        summary=f"Verify the `{record.name}` automation test flow.",
        preconditions=standard_preconditions(record.domain, mutating="mutating" in record.markers),
        steps=[
            TestLinkStep(1, "Prepare the EMS REST API session and test data through the automation fixtures.", "The test prerequisites are prepared."),
            TestLinkStep(2, f"Execute the REST API operation covered by `{record.name}`.", "The API response satisfies the automation assertions."),
            TestLinkStep(3, "Record the Allure/reporting testcase metadata and test result.", "The report can be traced back to the corresponding testcase id."),
        ],
        source=record.source,
        markers=list(record.markers),
    )


def session_backfill(record: TestCaseRecord) -> TestLinkCaseBackfill:
    if record.case_id == "EMS1-6640":
        steps = [
            TestLinkStep(1, "Call `POST /usersession` with readwrite, readonly, and noaccess role credentials.", "The API returns success and the response contains a session id."),
            TestLinkStep(2, "Call the logout API with the returned session id.", "The logout API returns success."),
        ]
    elif record.case_id == "EMS1-6651":
        steps = [
            TestLinkStep(1, "Log in to the EMS REST API with readwrite credentials.", "Login succeeds and a session id is returned."),
            TestLinkStep(2, "Call the logout API to delete the session.", "The logout API returns success."),
            TestLinkStep(3, "Call a protected API again with the deleted session.", "The API rejects the request and returns an invalid session or not authorized error."),
        ]
    elif record.case_id == "EMS1-7020":
        steps = [
            TestLinkStep(1, "Call `POST /usersession` with an invalid username or invalid password.", "The API rejects the login."),
            TestLinkStep(2, "Check the failure response.", "The response is a failure and the error message contains invalid username or invalid password."),
        ]
    else:
        steps = [
            TestLinkStep(1, "Call a protected API without a session or with an invalid session.", "The API rejects the request."),
            TestLinkStep(2, "Check the failure response.", "The response is a failure and the error message contains invalid session or not authorized."),
        ]

    return TestLinkCaseBackfill(
        external_id=record.case_id,
        name=record.name,
        summary=f"Verify the user session scenario: `{record.name}`.",
        preconditions="The EMS REST API is reachable, and test accounts are configured in auth_accounts/profile.",
        steps=steps,
        source=record.source,
        markers=list(record.markers),
    )


def invalid_param_backfill(record: TestCaseRecord) -> TestLinkCaseBackfill:
    return TestLinkCaseBackfill(
        external_id=record.case_id,
        name=record.name,
        summary=f"Verify `{record.domain}` API error handling for invalid parameters.",
        preconditions=standard_preconditions(record.domain, mutating="mutating" in record.markers),
        steps=[
            TestLinkStep(1, "Prepare the session and required test target through the automation fixtures.", "The prerequisites are prepared."),
            TestLinkStep(2, "Send API requests with missing, malformed, or invalid values according to the automation invalid-parameter matrix.", "The API must not accept the invalid request."),
            TestLinkStep(3, "Check the HTTP status, retstatus, and error message.", "The response matches the expected failure status, and the error message contains the keyword defined by the automation."),
        ],
        source=record.source,
        markers=list(record.markers),
    )


def permission_summary_backfill(record: TestCaseRecord) -> TestLinkCaseBackfill:
    role = record.role or "permission"
    return TestLinkCaseBackfill(
        external_id=record.case_id,
        name=record.name,
        summary=f"Summarize the `{role}` permission automation test results.",
        preconditions="The REST API test cases for the corresponding permission role have been collected and executed in the same pytest run.",
        steps=[
            TestLinkStep(1, f"Read the testcase results for the `{role}` role from the current test run.", "Executed test cases and their case ids are available."),
            TestLinkStep(2, "Summarize failed items and error messages.", "The summary testcase passes when all member test cases pass; if any member fails, the summary testcase fails and lists the failed items."),
        ],
        source=record.source,
        markers=list(record.markers),
    )


def auth_matrix_summary_backfill(record: TestCaseRecord) -> TestLinkCaseBackfill:
    role = record.role or "auth matrix"
    return TestLinkCaseBackfill(
        external_id=record.case_id,
        name=record.name,
        summary=f"Summarize the RAD external `{role}` permission matrix test results.",
        preconditions="pytest is run with `--auth-matrix`, and the RAD external permission matrix tests have completed.",
        steps=[
            TestLinkStep(1, f"Collect RAD external `{role}` permission matrix test results.", "Execution results are available for each API and permission combination."),
            TestLinkStep(2, "Check whether allowed and rejected permission results match the matrix definition.", "The results match the expected permission model; any mismatch is included in the summary failure."),
        ],
        source=record.source,
        markers=list(record.markers),
    )


def openapi_backfill(record: TestCaseRecord) -> TestLinkCaseBackfill:
    if record.case_id == "EMS1-7116":
        return TestLinkCaseBackfill(
            external_id=record.case_id,
            name=record.name,
            summary=(
                "Verify the latest EMS OpenAPI YAML file is synchronized with the current SwaggerUI "
                "/v3/api-docs key contract. This testcase focuses on YAML file correctness: paths, "
                "methods, parameters, request/response schema references, and schema leaf keys must match "
                "live Swagger. It does not verify whether the REST API function applies configuration to the device."
            ),
            preconditions=(
                "The EMS REST API is reachable. configs/ems.yaml points to the target EMS version. "
                "The latest NetAtlasEMS_OpenAPI_*.yaml file for that EMS version is available under the "
                "configured OpenAPI version directory or EMS_OPENAPI_YAML_FILE. Live Swagger /v3/api-docs "
                "is reachable; run this testcase with --run-live-swagger-check."
            ),
            steps=[
                TestLinkStep(
                    1,
                    "1. Read the configured EMS version from configs/ems.yaml and locate the latest "
                    "NetAtlasEMS_OpenAPI_*.yaml file for that version.\n"
                    "2. Fetch the current live Swagger OpenAPI document from /v3/api-docs.\n"
                    "3. Compare the latest YAML file with live Swagger using key contract comparison.\n"
                    "4. Report any key mismatch as a failure.",
                    "1. The latest YAML file exists and can be parsed as an OpenAPI document.\n"
                    "2. The live Swagger OpenAPI JSON is reachable and parseable.\n"
                    "3. Paths, HTTP methods, path/header/query parameter names, request/response schema "
                    "references, and schema leaf keys are synchronized between YAML and live Swagger.\n"
                    "4. If a key exists only in YAML or only in live Swagger, the testcase fails and lists "
                    "the added/removed key paths.",
                )
            ],
            source=record.source,
            markers=list(record.markers),
        )

    if record.case_id == "EMS1-7210":
        return TestLinkCaseBackfill(
            external_id=record.case_id,
            name=record.name,
            summary=(
                "Verify live Swagger /v3/api-docs is reachable and returns a usable OpenAPI document. "
                "This testcase checks the live Swagger service and document structure only; YAML file "
                "synchronization is covered by EMS1-7116."
            ),
            preconditions=(
                "The EMS REST API is reachable and the Swagger /v3/api-docs endpoint is enabled. "
                "Run this testcase with --run-live-swagger-check."
            ),
            steps=[
                TestLinkStep(
                    1,
                    "1. Fetch the current live Swagger OpenAPI document from /v3/api-docs.\n"
                    "2. Parse the response as JSON.\n"
                    "3. Verify the document declares an OpenAPI/Swagger version and contains non-empty "
                    "paths and components.schemas.",
                    "1. The live Swagger OpenAPI JSON is reachable and parseable.\n"
                    "2. The document includes an openapi/swagger version value.\n"
                    "3. The document contains non-empty paths and components.schemas, so automation can use "
                    "it as a live contract source.",
                )
            ],
            source=record.source,
            markers=list(record.markers),
        )

    return TestLinkCaseBackfill(
        external_id=record.case_id,
        name=record.name,
        summary=f"Verify the OpenAPI contract: `{record.name}`.",
        preconditions="The EMS profile and OpenAPI baseline are configured; live Swagger tests require EMS connectivity.",
        steps=[
            TestLinkStep(1, "Connect to the EMS live Swagger/OpenAPI endpoint.", "The live OpenAPI document is retrievable."),
            TestLinkStep(2, "Run the OpenAPI assertions defined by the automation.", "No unexpected OpenAPI differences are found."),
        ],
        source=record.source,
        markers=list(record.markers),
    )

def catalog_records() -> Iterable[TestLinkCaseBackfill]:
    for raw in catalog_test_cases():
        case_ids = raw.get("case_ids") or []
        if not case_ids:
            continue
        name = str(raw.get("name") or case_ids[0])
        markers = [str(item) for item in raw.get("markers") or []]
        api_calls = [str(item).upper() for item in raw.get("api_call_prefixes") or []]
        validations = [str(item) for item in raw.get("validation_refs") or []]
        config_refs = [str(item) for item in raw.get("config_data_refs") or []]
        action = "Call the REST API according to the automation testcase flow."
        if api_calls:
            action = f"Execute API operations according to the automation testcase flow: {', '.join(api_calls)}."
        expected = "The API response satisfies the automation assertions."
        if validations:
            expected = f"The response satisfies the validation conditions: {', '.join(validations)}."
        preconditions = "The EMS REST API is reachable, and the test profile, hardware, and auth settings are configured."
        if config_refs:
            preconditions += f" Required configuration data: {', '.join(config_refs)}."

        yield TestLinkCaseBackfill(
            external_id=str(case_ids[0]),
            name=name,
            summary=f"Verify the `{name}` automation test flow.",
            preconditions=preconditions,
            steps=[
                TestLinkStep(1, "Prepare the session, target, and test data through pytest fixtures.", "The test prerequisites are complete."),
                TestLinkStep(2, action, expected),
                TestLinkStep(3, "Clean up test data when needed and output report metadata.", "The environment returns to a stable state, and the report can be traced to the testcase id."),
            ],
            source="cases.case_catalog",
            markers=markers,
        )


def neox_records() -> Iterable[TestLinkCaseBackfill]:
    for case in DIRECT_NEOX_READWRITE_CASES.values():
        yield neox_config_backfill(case.case_id, case.name)

    for profile_type in PROFILE_TYPES:
        for offset, name in PROFILE_OPERATION_OFFSETS.values():
            case_id = f"EMS1-{7134 + PROFILE_TYPES.index(profile_type) * 4 + offset}"
            yield neox_profile_backfill(case_id, f"{name}[{profile_type}]", profile_type)


def neox_config_backfill(case_id: str, name: str) -> TestLinkCaseBackfill:
    if case_id == "EMS1-7223":
        return TestLinkCaseBackfill(
            external_id=case_id,
            name=name,
            summary="Verify applying the NeoX SFU provision template to an ONT through REST API.",
            preconditions="Run with `--run-neox-config`; target node, ONT SN/id, REST readwrite account, and CLI credentials are configured. This testcase creates NeoX profile data and changes ONT configuration in a controlled test environment.",
            steps=[
                TestLinkStep(
                    1,
                    "Verify that the NeoX target data, ONT SN/id, REST session, and CLI connectivity are available.",
                    "The target data is complete, the REST session is valid, and the node is reachable.",
                ),
                TestLinkStep(
                    2,
                    "Create or ensure the prerequisite NeoX profiles through REST API: bandwidth profile, security profile, service profiles, UNI profile, and template profile.",
                    "Each profile REST request returns success, and the SFU template profile references the required prerequisite profiles.",
                ),
                TestLinkStep(
                    3,
                    "Apply `#RestApi_provision_temp_SFU` to the target ONT through `POST /configNeoXSeries/interface/remote/{device}/{slot}/{port}/{ont}`.",
                    "The REST API returns success for the ONT configuration request.",
                ),
                TestLinkStep(
                    4,
                    "Poll `GET /ont/sn/{sn}` until the ONT description and template name are visible in the REST readback.",
                    "The REST readback contains the target ONT id, SN, `REST_API_PROVISION_TEMPLATE_SFU`, and `#RestApi_provision_temp_SFU`.",
                ),
                TestLinkStep(
                    5,
                    "Verify the ONT configuration through NeoX CLI show commands.",
                    "The CLI output contains the target remote XONT, SN, description, admin state, and template name.",
                ),
                TestLinkStep(
                    6,
                    "Clean up the temporary ONT configuration and restore the baseline ONT state through the automation cleanup flow.",
                    "Cleanup completes successfully and the environment is stable for subsequent tests.",
                ),
            ],
            source="cases.neox_case_ids",
            markers=["neox_config", "mutating", "readwrite", "ont", "provision_template_sfu"],
        )
    scenario = neox_scenario(name)
    feature = neox_feature(name)
    if scenario == "clear":
        steps = [
            TestLinkStep(1, f"Verify that NeoX `{feature}` target data and CLI connectivity are available.", "Target data is complete and the node is reachable."),
            TestLinkStep(2, f"Clear the `{feature}` configuration through the REST API.", "The REST API returns success."),
            TestLinkStep(3, "Verify through CLI `show running-config` that the configuration has been restored or cleared.", "The CLI output does not contain configuration tokens that should have been cleared."),
        ]
    elif scenario in {"min", "max"}:
        steps = [
            TestLinkStep(1, f"Verify NeoX `{feature}` target data and clear any existing test configuration.", "The test target is available and the initial state is clean."),
            TestLinkStep(2, f"Send the `{scenario}` payload to create the `{feature}` configuration.", "The REST API returns success."),
            TestLinkStep(3, "Verify the configuration through CLI `show running-config`.", "The CLI output contains the expected tokens or visible lines defined by the automation."),
        ]
    else:
        steps = neox_config_error_steps(feature)
    return TestLinkCaseBackfill(
        external_id=case_id,
        name=name,
        summary=f"Verify NeoX `{feature}` `{scenario}` REST configuration behavior.",
        preconditions="Run with `--run-neox-config`; target node, profile, hardware, and CLI credentials are configured. This testcase changes device configuration and must run in a controlled test environment.",
        steps=steps,
        source="cases.neox_case_ids",
        markers=["neox_config", "mutating", "readwrite", feature, scenario],
    )


def neox_config_error_steps(feature: str) -> list[TestLinkStep]:
    case_matrix = {
        "ge": (
            "Send the NeoX GE invalid configuration matrix, including invalid enum values and device CLI-level validation cases such as an over-length port name.",
            "API/schema-layer cases return the expected failure status and stable message such as `Invalid JSON input`; device CLI-layer cases return failure with a non-empty error message without requiring exact CLI wording.",
        ),
        "nni": (
            "Send the NeoX NNI invalid configuration matrix: invalid `portenable`, invalid `mode`, `mtu` above range, and `pvid` above range.",
            "The REST API must not accept any invalid NNI payload. API/schema-layer failures are checked against stable status/message contracts; device CLI-layer failures only require failure plus a non-empty error message.",
        ),
        "vlan": (
            "Send the NeoX VLAN invalid configuration matrix: invalid `tpid`, invalid `fixedport` syntax, invalid `untaggedport` syntax, and invalid `forbiddenport` syntax.",
            "The REST API must not create or update the VLAN with invalid data. API/schema-layer failures are checked against stable status/message contracts; device CLI-layer failures only require failure plus a non-empty error message.",
        ),
        "ont": (
            "Run the NeoX ONT invalid configuration matrix with `--run-neox-ont-error`, using runtime target SN/password data and the configured ONT negative cases.",
            "Every invalid ONT payload must be rejected. API/schema-layer failures are checked against stable status/message contracts; device CLI-layer failures only require failure plus a non-empty error message.",
        ),
    }
    action, expected = case_matrix.get(
        feature,
        (
            f"Send invalid NeoX `{feature}` configuration payloads according to the negative case matrix.",
            "The REST API rejects each invalid payload. Stable API/schema errors are checked precisely; device CLI errors are checked as failure with a non-empty message.",
        ),
    )
    return [
        TestLinkStep(
            1,
            f"Verify NeoX `{feature}` target data, REST session, and required cleanup state.",
            "The target data is complete, the REST session is valid, and the test can safely run in the controlled NeoX environment.",
        ),
        TestLinkStep(2, action, expected),
        TestLinkStep(
            3,
            "Record the actual HTTP status, retstatus, retresult/message, and redacted response body in the automation report.",
            "The report identifies whether each case was validated as an API/schema-layer error or a device CLI-layer error, and no invalid request is reported as successful.",
        ),
        TestLinkStep(
            4,
            f"Clean up the NeoX `{feature}` test configuration through the automation cleanup flow.",
            "The environment is returned to a stable state for subsequent test cases.",
        ),
    ]


def neox_profile_backfill(case_id: str, name: str, profile_type: str) -> TestLinkCaseBackfill:
    scenario = neox_scenario(name)
    if scenario == "clear":
        steps = [
            TestLinkStep(1, f"Verify the `{profile_type}` test profile name and CLI connectivity.", "Profile target data is available."),
            TestLinkStep(2, f"Clear or delete the `{profile_type}` test profile through the REST API.", "The REST API returns success or an acceptable not-found state."),
            TestLinkStep(3, "Verify through REST or CLI that the profile has been cleared.", "The query result matches the expected post-clear state."),
        ]
    elif scenario in {"min", "max"}:
        steps = [
            TestLinkStep(1, f"Prepare the `{profile_type}` `{scenario}` payload and a unique profile name.", "The payload can be loaded from the automation configuration."),
            TestLinkStep(2, f"Create the `{profile_type}` profile through the REST API.", "The REST API returns success."),
            TestLinkStep(3, "Query the REST response and compare CLI expected tokens when required.", "The profile content matches the payload and automation expectations."),
        ]
    else:
        steps = [
            TestLinkStep(
                1,
                f"Load the `{profile_type}` profile error matrix from the automation configuration.",
                "Negative case data is readable and includes the configured API/schema or device CLI error layer.",
            ),
            TestLinkStep(
                2,
                f"Delete the existing `{profile_type}` test profile, then send each invalid profile payload through the REST API.",
                "The invalid POST request does not succeed and the test profile is left available for cleanup.",
            ),
            TestLinkStep(
                3,
                "Validate the failure response according to the configured error layer.",
                "API/schema-layer cases match the stable status or message contract; device CLI-layer cases return failure with a non-empty error message without requiring exact CLI wording.",
            ),
            TestLinkStep(
                4,
                "Attach the automation error-matrix report and cleanup the test profile.",
                "The report records request, response, expected assertion mode, and zero mismatches for the profile type.",
            ),
        ]
    return TestLinkCaseBackfill(
        external_id=case_id,
        name=name,
        summary=f"Verify NeoX profile `{profile_type}` `{scenario}` REST configuration behavior.",
        preconditions="Run with `--run-neox-config`; NeoX profile test data, target node, and CLI credentials are configured. This testcase changes profile configuration and must run in a controlled test environment.",
        steps=steps,
        source="cases.neox_case_ids",
        markers=["neox_config", "profile", "mutating", "readwrite", profile_type, scenario],
    )


def standard_preconditions(domain: str, *, mutating: bool) -> str:
    text = f"The EMS REST API is reachable; `configs/` contains the profile, auth, and hardware target required for `{domain}` tests."
    if mutating:
        text += " This testcase creates, modifies, or deletes test data and must run in a controlled test environment with the cleanup flow enabled."
    return text


def expected_success_text(expected_success: bool) -> str:
    if expected_success:
        return "The HTTP response has a success status; if the response contains `retstatus`, it must be `Success`."
    return "The HTTP response has the expected failure status, and the error message matches the testcase definition."


def describe_path(case: EndpointCase) -> str:
    if isinstance(case.path, str):
        return case.path
    return f"<dynamic path for {case.name}>"


def neox_feature(name: str) -> str:
    for feature in ("ge", "nni", "vlan", "ont"):
        if f"_{feature}_" in f"_{name}_":
            return feature
    return "profile"


def neox_scenario(name: str) -> str:
    for scenario in ("clear", "min", "max", "error"):
        if f"_{scenario}_" in f"_{name}_":
            return scenario
    return "unknown"


def case_sort_key(case: TestLinkCaseBackfill) -> tuple[int, str]:
    prefix, _, number = case.external_id.partition("-")
    try:
        return (int(number), prefix)
    except ValueError:
        return (10**9, case.external_id)


def write_json(cases: list[TestLinkCaseBackfill], output: Path) -> None:
    payload = [case_to_json(case) for case in cases]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_csv(cases: list[TestLinkCaseBackfill], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "external_id",
                "name",
                "summary",
                "preconditions",
                "step_number",
                "actions",
                "expected_results",
                "source",
                "markers",
            ],
        )
        writer.writeheader()
        for case in cases:
            for step in case.steps:
                writer.writerow(
                    {
                        "external_id": case.external_id,
                        "name": case.name,
                        "summary": case.summary,
                        "preconditions": case.preconditions,
                        "step_number": step.step_number,
                        "actions": step.actions,
                        "expected_results": step.expected_results,
                        "source": case.source,
                        "markers": ",".join(case.markers),
                    }
                )


def case_to_json(case: TestLinkCaseBackfill) -> dict[str, Any]:
    data = asdict(case)
    data["steps"] = [asdict(step) for step in case.steps]
    return data


def apply_to_testlink(cases: list[TestLinkCaseBackfill], url: str, devkey: str, *, version: int) -> None:
    client = xmlrpc.client.ServerProxy(url, allow_none=True)
    for case in cases:
        args = {
            "devKey": devkey,
            "testcaseexternalid": case.external_id,
            "version": version,
            "summary": case.summary,
            "preconditions": case.preconditions,
            "steps": [
                {
                    "step_number": step.step_number,
                    "actions": step.actions,
                    "expected_results": step.expected_results,
                    "execution_type": step.execution_type,
                }
                for step in case.steps
            ],
        }
        result = client.tl.updateTestCase(args)
        if isinstance(result, list):
            result = result[0] if result else {}
        status = result.get("status") if isinstance(result, dict) else None
        if status is False:
            raise RuntimeError(f"TestLink update failed for {case.external_id}: {result}")
        print(f"updated {case.external_id} {case.name}")


def apply_with_testlink_agent(
    cases: list[TestLinkCaseBackfill],
    *,
    agent: Path,
    env_file: Path | None,
    version: int,
    write: bool,
    output: Path,
    stop_on_error: bool,
) -> int:
    if not agent.exists():
        raise FileNotFoundError(f"UseTestlink agent does not exist: {agent}")

    run_dir = output.parent / "testlink_agent_payloads"
    run_dir.mkdir(parents=True, exist_ok=True)
    results: list[dict[str, Any]] = []
    failures = 0

    for case in cases:
        case_dir = run_dir / safe_filename(case.external_id)
        case_dir.mkdir(parents=True, exist_ok=True)
        summary_file = case_dir / "summary.txt"
        preconditions_file = case_dir / "preconditions.txt"
        steps_file = case_dir / "steps.json"
        summary_file.write_text(case.summary, encoding="utf-8")
        preconditions_file.write_text(case.preconditions, encoding="utf-8")
        steps_file.write_text(
            json.dumps([asdict(step) for step in case.steps], indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

        command = [
            sys.executable,
            str(agent),
        ]
        if env_file is not None:
            command.extend(["--env-file", str(env_file)])
        command.extend(
            [
                "update-testcase",
                "--testcase-external-id",
                case.external_id,
                "--version",
                str(version),
                "--summary-file",
                str(summary_file.resolve()),
                "--preconditions-file",
                str(preconditions_file.resolve()),
                "--steps-file",
                str(steps_file.resolve()),
                "--execution-type",
                "automated",
            ]
        )
        if write:
            command.append("--write")

        completed = subprocess.run(
            command,
            cwd=str(agent.parent),
            text=True,
            capture_output=True,
            encoding="utf-8",
            errors="replace",
            check=False,
        )
        result = {
            "external_id": case.external_id,
            "name": case.name,
            "mode": "write" if write else "preview",
            "returncode": completed.returncode,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "payload_dir": str(case_dir),
        }
        results.append(result)
        if completed.returncode == 0:
            print(f"{'updated' if write else 'previewed'} {case.external_id} {case.name}")
        else:
            failures += 1
            print(f"failed {case.external_id} {case.name}: returncode={completed.returncode}", file=sys.stderr)
            if stop_on_error:
                break

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(
            {
                "mode": "write" if write else "preview",
                "agent": str(agent),
                "env_file": str(env_file) if env_file else None,
                "requested_count": len(cases),
                "completed_count": len(results),
                "failure_count": failures,
                "results": results,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    return 0 if failures == 0 else 2


def safe_filename(value: str) -> str:
    return "".join(char if char.isalnum() or char in ("-", "_", ".") else "_" for char in value)


def parse_case_filter(values: list[str]) -> set[str]:
    return {value.strip() for value in values if value.strip()}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or apply TestLink step/expected backfill from automation metadata.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output path for dry-run export.")
    parser.add_argument("--format", choices=("json", "csv"), default="json", help="Dry-run export format.")
    parser.add_argument("--case-id", action="append", default=[], help="Limit to one testcase external id. Can be repeated.")
    parser.add_argument("--apply", action="store_true", help="Write changes to TestLink through XML-RPC.")
    parser.add_argument("--url", default=os.getenv("TESTLINK_XMLRPC_URL"), help="TestLink XML-RPC endpoint URL.")
    parser.add_argument("--devkey", default=os.getenv("TESTLINK_DEVKEY"), help="TestLink API devKey.")
    parser.add_argument("--version", type=int, default=1, help="TestLink testcase version to update.")
    parser.add_argument(
        "--use-testlink-agent",
        type=Path,
        help="Run updates through UseTestlink testlink_agent.py instead of the built-in XML-RPC updater.",
    )
    parser.add_argument("--agent-env-file", type=Path, help="Env file passed to UseTestlink via --env-file.")
    parser.add_argument(
        "--agent-write",
        action="store_true",
        help="Pass --write to UseTestlink. Omit for UseTestlink preview mode.",
    )
    parser.add_argument(
        "--agent-output",
        type=Path,
        default=DEFAULT_AGENT_RESULTS,
        help="JSON result log for UseTestlink preview/write runs.",
    )
    parser.add_argument("--stop-on-error", action="store_true", help="Stop UseTestlink batch on first failed testcase.")
    args = parser.parse_args()

    cases = build_backfill_cases()
    filters = parse_case_filter(args.case_id)
    if filters:
        cases = [case for case in cases if case.external_id in filters]

    if args.use_testlink_agent:
        return apply_with_testlink_agent(
            cases,
            agent=args.use_testlink_agent,
            env_file=args.agent_env_file,
            version=args.version,
            write=args.agent_write,
            output=args.agent_output,
            stop_on_error=args.stop_on_error,
        )

    if args.apply:
        if not args.url or not args.devkey:
            parser.error("--apply requires --url/TESTLINK_XMLRPC_URL and --devkey/TESTLINK_DEVKEY")
        apply_to_testlink(cases, args.url, args.devkey, version=args.version)
        return 0

    if args.format == "json":
        write_json(cases, args.output)
    else:
        write_csv(cases, args.output)
    print(f"wrote {len(cases)} testcase backfill record(s) to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

